name: FillUp
version: 0.5
main: org.coleski123.fillup.FillUp
api-version: '1.20'
description: A plugin allowing owners/admins to fill containers with a simple command
commands:
  fillup:
    description: Fill a chest with a specified item.
    usage: /fillup <item_name> <amount>
permissions:
  fillup.use:
    description: Allows players to use the /fillup command
    default: op
