Prefix: "&5[FillUp] "
Options:
  ChatMessages: true
  ContainerMessages: true
ChatMessages:
  Message1: "&6{CONTAINERNAME} filled with {AMOUNT1} {ITEM}"
  Message2: "&6Only {AMOUNT1} out of {AMOUNT2} {ITEM} could fit in the {CONTAINERNAME}."
  Message3: "&4The {CONTAINERNAME} does not have enough space for these items."
  Message4: "&4You must be looking at a container to use this command."
  Message5: "&4You do not have permission to use this command!"
ContainerMessages:
  Message1: "&6{CONTAINERNAME} filled with {AMOUNT1} {ITEM}"
  Message2: "&6Only {AMOUNT1} out of {AMOUNT2} {ITEM} could fit in the {CONTAINERNAME}."
  Message3: "&4The {CONTAINERNAME} does not have enough space for these items."
  Message4: "&4You must be looking at a container to use this command."
